title: Devin Horvay
author: Devin Horvay
baseurl: ""
url: "https://dhorvay.github.io/"
github_username: dhorvay
logo: /assets/img/profile.jpeg

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

github: [metadata]