title: Hello!
author: Devin Horvay
baseurl: ""
url: "https://dhorvay.github.io/"
github_username: dhorvay

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

github: [metadata]